otterdog/eclipse-tractusx.jsonnet

The ontology repo should be deleted, see: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3459

Delete ontology repo

---

otterdog/eclipse-tractusx.jsonnet

As requested in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3500

Add tutorial-resources repo

---

otterdog/eclipse-tractusx.jsonnet

As requested in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3516
Please review the name and settings of the repo, I used all lower case.

Add pcf-exchange-kit repo

---

otterdog/eclipse-tractusx.jsonnet

Requested in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3533

Enable gh-pages for repo tutorial-resources

---

otterdog/eclipse-tractusx.jsonnet

As requested in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3515

Create eco-pass-kit repo

---

otterdog/eclipse-tractusx.jsonnet

As requested in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3543

Move SWAGGER related secrets to org level

---

otterdog/eclipse-tractusx.jsonnet

chore: new repo sig-security

---

otterdog/eclipse-tractusx.jsonnet

This PR represents a request for a new repository named `identity-trust`, the purpose of which will be 
to host specification documents regarding topics revolving around identity and trust (a.k.a. "SSI")
\cc @jimmarino @wolf4ood @matgnt @dr-markus @borisrizov-zf
I hope the configuration regarding `gh-pages` is correct, especially the part about the `gh_pages_build_type`, I merely copied it over from another repo. 

feat: request for new repository

---

otterdog/eclipse-tractusx.jsonnet

Enable discussions to discuss security stuff in sig-security.
... no changes to dependencies or files.

feat: enable discussions in sig-security

---

otterdog/eclipse-tractusx.jsonnet

PR to enable Discussions at Item Relationship Service repository.
Fixes https://github.com/eclipse-tractusx/sig-infra/issues/290

feat: add Discussions to Item Relationship Service repo

---

otterdog/eclipse-tractusx.jsonnet

Based on this request https://github.com/eclipse-tractusx/sig-infra/issues/338 gh-pages branch is created and GitHub Pages is enabled for the https://github.com/eclipse-tractusx/managed-identity-wallet repo.

chore: add gh-pages to managed-identity-wallet repo

---

otterdog/eclipse-tractusx.jsonnet

EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4020

Add sonarcloud to policy-hub repo.

---

otterdog/eclipse-tractusx.jsonnet

Based on this issue https://github.com/eclipse-tractusx/sig-infra/issues/393. Creating new esc-backbone repo so the team can make their initial contribution to the project.

chore: add esc-backbone repo

---

otterdog/eclipse-tractusx.jsonnet

Based on request from IRS team. Fixes https://github.com/eclipse-tractusx/sig-infra/issues/410.

feat: add homepage to item-relationship-service repo

---

otterdog/eclipse-tractusx.jsonnet

Add ssi-authority-schema-registry and ssi-credential-issuer repositories
Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4222

Add ssi-authority-schema-registry and ssi-credential-issuer

---

otterdog/eclipse-tractusx.jsonnet

Add new repository sig-testing (similiar to sig-security, sig-infra, ...)

Add repository sig-testing

---

otterdog/eclipse-tractusx.jsonnet

- archive repo managed-identity-wallets-archived
fixes https://github.com/eclipse-tractusx/sig-infra/issues/450
FYI @AngelikaWittek

chore: archive repo managed-identity-wallets-archived

---

otterdog/eclipse-tractusx.jsonnet

- archive repo https://github.com/eclipse-tractusx/ssi-docu
fixes https://github.com/eclipse-tractusx/sig-infra/issues/451
FYI @AngelikaWittek @paullatzelsperger

chore: archive repo ssi-docu

---

otterdog/eclipse-tractusx.jsonnet

archive repos:
- https://github.com/eclipse-tractusx/daps-helm-chart
- https://github.com/eclipse-tractusx/daps-registration-service 
fixes https://github.com/eclipse-tractusx/sig-infra/issues/449
FYI @AngelikaWittek @MehranRoshandel

chore: archive repo daps repositories

---

otterdog/eclipse-tractusx.jsonnet

- align 'new' ssi repos and policy-hub with common repo settings
- add branch protection

chore: align with common settings and add branch protection

---

otterdog/eclipse-tractusx.jsonnet

- archive https://github.com/eclipse-tractusx/tractusx-quality-checks repo
fixes https://github.com/eclipse-tractusx/sig-infra/issues/453

chore: archive repo tractusx-quality-checks

---

otterdog/eclipse-tractusx.jsonnet

This PR enables merge commits in the BPN-DID-Resolution-Service repo. It is needed when doing GH Releases, because otherwise the GH commit history 
of the `releases` branch gets messed up.

chore: enable merge commits for BDRS

---

otterdog/eclipse-tractusx.jsonnet

PR to create new repository 'api-hub' to host/publish products' APIs via GitHub Pages. 
@Siegfriedk please approve.

chore: add api-hub repository

---

otterdog/eclipse-tractusx.jsonnet

-  add new repo `emergingtechnologies`
@felixatdlr repo will created with the following settings
```yaml
delete_branch_on_merge: true
orgs.newBranchProtectionRule('main') {
required_approving_review_count: 1,
```
details to options can be found [here](https://github.com/EclipseFdn/otterdog-defaults/blob/main/otterdog-defaults.libsonnet) 
fixes https://github.com/eclipse-tractusx/sig-infra/issues/486
@Siegfriedk  @giterrific @stephanbcbauer @danielmiehle please review and give your thumbs up for creating this new repo 
Thanks in advance.

chore: add new repo archive repo emergingtechnologies

---

otterdog/eclipse-tractusx.jsonnet

Add Helm secrets and variables that were requested in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4638

feat: Add Helm secrets and variables

---

otterdog/eclipse-tractusx.jsonnet

Add sonar variables and secrets for project: ssi-authority-schema-registry
Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4732

Add sonar variables/secrests for ssi authority schema registry

---

otterdog/eclipse-tractusx.jsonnet

- remove branch protection for dev branch as dev branches are retired, change to less strict branch protection for main branch of portal repo to enable auto deployment triggered by bot https://github.com/eclipse-tractusx/portal/issues/243
- add homepage to shared components
- remove obsolete environments from portal-backend

chore: update branch protection, homepage and envs

---

otterdog/eclipse-tractusx.jsonnet

feat: enable github pages for knowledge-agents-aas-bridge

---

otterdog/eclipse-tractusx.jsonnet

This PR will archive the [eclipse-tractusx/emergingtechnologies](https://github.com/eclipse-tractusx/emergingtechnologies) repository. All contributions have been done and went through project contribution checks.
There is no one actively maintaining it from now on.
FYI: @AngelikaWittek

chore: archive emergingtechnologies

---

otterdog/eclipse-tractusx.jsonnet

update description for portal assets repo to improve transparency

chore: update description for portal assets repo

---

otterdog/eclipse-tractusx.jsonnet

New repository setup for wallet DIM stub application 
ref: https://github.com/eclipse-tractusx/sig-release/issues/788

feat: new repo for wallet-dim-stub application

---

otterdog/eclipse-tractusx.jsonnet

Change docker.com token path for secret

Docker token name harmonization

---

otterdog/eclipse-tractusx.jsonnet

deprecate unmaintained repos
https://github.com/eclipse-tractusx/.eclipsefdn/issues/112

chore: deprecate unmaintained repos

---

otterdog/eclipse-tractusx.jsonnet

Requests a new repository `tractusx-identityhub`

chore: request new repository tractusx-identityhub

---

otterdog/eclipse-tractusx.jsonnet

Requests new repository `tractusx-issuerservice`

chore: request new repository tractusx-issuerservice

---

otterdog/eclipse-tractusx.jsonnet

Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5761

Add develocity token

---

otterdog/eclipse-tractusx.jsonnet

Adds the DT Pull Service and the Test Orchestrator repositories.
Sig-release:
https://github.com/eclipse-tractusx/sig-release/issues/1159
- [ x ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ x ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

feat: Add test-orchestrator repo configuration
