eclipse-tractusx/.eclipsefdn

- otterdog/eclipse-tractusx.jsonnet
---
name: Enable GitHub Pages for data-exchange-test-service
about: 'Currently branch does not exist and GH Pages are disabled so helm repository is not available and helm chart is not released properly'
title: 'chore: enable gh-pages for data-exchange-test-service'
---
Thanks for opening this contribution!
_What does this PR introduce? Does it fix a bug? Does it add a new feature? Is it enhancing documentation?_
Currently branch does not exist and GH Pages are disabled so helm repository is not available and helm chart is not released properly
- To request a review, check out [who's involved](https://projects.eclipse.org/projects/automotive.tractusx/who) to see a list of contributors and …
> chore: enable gh-pages for data-exchange-test-service

- otterdog/eclipse-tractusx.jsonnet
Rename repo `community` to `sig-project-managment`
Fixes [GitLab Issue](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3324#note_1158954)
- To request a review, check out [who's involved](https://projects.eclipse.org/projects/automotive.tractusx/who) to see a list of contributors and committers
- Use the [mailing list](https://accounts.eclipse.org/mailing-list/tractusx-dev) if you are unsure, who to contact, or if want to engage in a general discussion
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to-contribute)
- Check out our [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)
- Check out the [Eclipse Foundation …
> chore: rename community repository

- otterdog/eclipse-tractusx.jsonnet
As discussed in the [Eclipse help desk ticket 3385](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3385#note_1178908), we would like to merge the `puris-frontend` and `puris-backend` repository into a new `puris` repository.
This pull requests updates the otterdog configuration to add the new repo.
> feat: new repository puris

- otterdog/eclipse-tractusx.jsonnet
I started to reference secrets available in the cbi pass repo, please double check.
There are some duplicates like veracode secrets, and others are not available yet, like sonar or azure credentials. If you know where these secrets are stored atm, please let me know.
> Reference secrets available in cbi pass repo

- otterdog/eclipse-tractusx.jsonnet
Adding new repo `eclipse-tractusx.github.io.largefiles`, as requested in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3499
Git LFS settings have to be configured locally and persisted in `.gitattributes` after repo creation
> Add large files repo for website assets

- otterdog/eclipse-tractusx.jsonnet
As discussed in #10, the new `puris` repository substitutes the old repos `puris-frontend` and `puris-backend`. Since the new repository is created including an initial contribution in https://github.com/eclipse-tractusx/puris/pull/1, the old repositories aren't used anymore and can therefore be deleted.
> chore: remove puris-frontend and puris-backend repo

- otterdog/eclipse-tractusx.jsonnet
This PR enables GitHub pages for the [sig-release](https://github.com/eclipse-tractusx/sig-release) repo.
Settings are "copied" from other repos with enabled GitHub pages
We are currently building automation, that runs checks on our org and compiles the results to a statically generated dashboard. This dashboard should be hosted via GitHub pages.
FYI: @Siegfriedk
> Enable GitHub pages for `sig-release` repo

- otterdog/eclipse-tractusx.jsonnet
The DMC Team decided to use only one (already existing repo): demand-capacity-mgmt.
Fixes https://github.com/eclipse-tractusx/sig-infra/issues/223
> chore: delete dmc frontend backend repo

- otterdog/eclipse-tractusx.jsonnet
update repository settings for portal-repository:
- change default branch (issue: https://github.com/eclipse-tractusx/portal-cd/issues/66)
- add branch protections rule
- add 'delete branch on merge' setting
- add repo description
> chore: update settings for portal repos

- otterdog/eclipse-tractusx.jsonnet
index.yaml is present on the gh-pages branch but github pages is disabled and not available as a helm repo
> chore: enable github pages for sd-factory repo

- otterdog/eclipse-tractusx.jsonnet
add new repository `knowledge-agents-aas-bridge` to eclipse-tractusx GH org as requested in eclipse-tractusx/sig-infra#240
> chore: add new repository

- otterdog/eclipse-tractusx.jsonnet
We (security team at EF: https://www.eclipse.org/security/team/) would like to enable secret scanning for all of the repos of eclipse projects hosted on GitHub. For that purpose we suggest changes to the configuration that the project leads can review.
> Enable secret scanning for all repos

- otterdog/eclipse-tractusx.jsonnet
Currently, the discussion section for [tutorial-resources](https://github.com/eclipse-tractusx/tutorial-resources) is not activated. This PR activates the section.
Discussions are needed for development
> chore: added discussion section to tutorial-resources repo

- otterdog/eclipse-tractusx.jsonnet
- disable projects on repo base
https://eclipse-tractusx.github.io/.eclipsefdn/repo-sig-release/
> chore: disable projects on repo sig-release

- otterdog/eclipse-tractusx.jsonnet
PR to archive traceability-foss-backend as per https://github.com/eclipse-tractusx/traceability-foss-backend/issues/55.
> chore: archive traceability-foss-backend repo

- .tractusx
PR to add tractusx metadata following https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5. 
> chore: add tractusx metadata

- otterdog/eclipse-tractusx.jsonnet
Adding a new uninitialized repo `bpdm-certificate-management`, liked requested in eclipse-tractusx/sig-infra#310 
FYI @SujitMBRDI , @nicoprow. Please initialize the repository with at least the legal docs, as soon as it is created
> chore: add new bpdm-certificate-management repo

- otterdog/eclipse-tractusx.jsonnet
- add delete branch on merge to repo `eclipse-tractusx.github.io`
referring to https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/401#issuecomment-1766365398
> chore: enable delete branch on merge

- otterdog/eclipse-tractusx.jsonnet
- add branch protection main branch on `sig-release` repo
guided information from EF and Otterdog Team https://github.com/eclipse-tractusx/.eclipsefdn/issues/28
current config see: https://eclipse-tractusx.github.io/.eclipsefdn/repo-sig-release/
FYI @stephanbcbauer @RolaH1t @kelaja @mabige
> chore: enable branch protection sig-release main branch

- otterdog/eclipse-tractusx.jsonnet
There are some standalone KIT repositories, containing some markdown files. The exact same files are used to build our [eclipse-tractusx.github.io](https://eclipse-tractusx.github.io/) website. 
This means we are duplicating content and even add more maintenance effort for keeping legal documentation up-to-date.
The repositories in question are:
- [eclipse-tractusx/eco-pass-kit](https://github.com/eclipse-tractusx/eco-pass-kit)
- [eclipse-tractusx/pcf-exchange-kit](https://github.com/eclipse-tractusx/pcf-exchange-kit)
- [eclipse-tractusx/online-simulation-kit](https://github.com/eclipse-tractusx/online-simulation-kit)
The KITs representation on our webiste:
- [Eco Pass KIT](https://eclipse-tractusx.github.io/docs-kits/kits/Eco_Pass_KIT/page-adoption-view)
- [PCF Exchange …
> chore: archive standalone KIT repos

- otterdog/eclipse-tractusx.jsonnet
This PR requests a new repository named 'tx-profiles'.
> chore: request new repo 'tx-profiles'

- otterdog/eclipse-tractusx.jsonnet
Please describe your PR: 
- add description for traceability-foss repo
fixes https://github.com/eclipse-tractusx/sig-infra/issues/407
@ds-mwesener @jzbmw 
Please check and give a feedback that this is approved by you. Then @netomi could overtake.
> chore: add description for traceability-foss repo

- otterdog/eclipse-tractusx.jsonnet
Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4244
> Add NUGET_API_KEY

- otterdog/eclipse-tractusx.jsonnet
Currently in PURIS repository the helm releaser action is not creating a release for the helm chart:  https://github.com/eclipse-tractusx/puris/actions/runs/8048107001
According to the documentation of the [chart-releaser action](https://github.com/helm/chart-releaser-action) "In your repo, go to Settings/Pages. Change the Source Branch to gh-pages."
The otterdog settings are copied from item-relationship-service repo and should do this configuration.
@tomaszbarwicki FYI
> Feat: Configure gh-pages for puris repository

- otterdog/eclipse-tractusx.jsonnet
- rename e2e-testing repo to tractus-x-umbrella
fixes https://github.com/eclipse-tractusx/sig-infra/issues/427
FYI @almadigabor @evegufy 
> chore: rename e2e-testing repo to tractus-x-umbrella

- otterdog/eclipse-tractusx.jsonnet
Requesting a new template repository, which will serve as starting point for everyone who wants to create their
own variant (="distribution") of EDC.
> chore: request new template repo

- otterdog/eclipse-tractusx.jsonnet
This PR creates a new repository and enabled github pages to move over https://github.com/catenax-ng/product-ontology repository from catenax-ng. The name `ontology-models` is just a suggestion I have, can be changed on request.
Related issue: https://github.com/eclipse-tractusx/sig-infra/issues/446
@Siegfriedk @stephanbcbauer @danielmiehle @giterrific please confirm/review.
> chore: add ontology-models repo

- otterdog/eclipse-tractusx.jsonnet
This PR requests a new repository `bpn-did-resolution-service` which is a Tractus-X shared service that will provide a scalable functionality to resolve BPN (Business Partner Number) -> DID (Decentralized Identifier).
Tractus-X uses BPNs as stable identifiers, but DID are used to represent the participant in an self-sovereign-identity context. Thus a resolution is necessary.
> chore: request new repository for BPN<>DID resolution service

- otterdog/eclipse-tractusx.jsonnet
- remove repo https://github.com/eclipse-tractusx/asset-tracking-platform
- remove repo https://github.com/eclipse-tractusx/esc-backbone
fixes https://github.com/eclipse-tractusx/sig-infra/issues/448
FYI @AngelikaWittek 
> chore: remove unused repos asset-tracking-platform + esc-backbone

- otterdog/eclipse-tractusx.jsonnet
Also enabled GitHub Pages for the new repository.
Related to [this issue](https://github.com/eclipse-tractusx/sig-infra/issues/475).
@Siegfriedk please approve.
> chore: add bpdm-upload-tool repository

- otterdog/eclipse-tractusx.jsonnet
> fix: Fixed helm repo URLs

- otterdog/eclipse-tractusx.jsonnet
This PR moves the currently-used username/password based auth over to using token-based auth, as required by OSSRH
please find related information in this [EF helpdesk issue](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4733)
> fix(auth): use OSSRH's tokenbased auth

- otterdog/eclipse-tractusx.jsonnet
Recent pr #81 didn't consider CodeQl workflow as a reused one (wrong).
This pr handles CodeQl as reusable workflow (correct, following the results in this [pr](https://github.com/eclipse-tractusx/puris/pull/450)).
> fix(puris): use syntax for reusable workflow for CodeQl

- otterdog/eclipse-tractusx.jsonnet
I got issues to correctly configure codeQl as mandatory. I'll raise an issue to clarify but thill clarification I don't want my PRs to be blocked.
> fix(puris): remove codeql as mandatory workflow

- otterdog/eclipse-tractusx.jsonnet
PR to enable branch protection and deletion after merge for api-hub repository.
> chore: enable branch protection and deletion after merge

- otterdog/eclipse-tractusx.jsonnet
- Added branch protection main branch on [digital-product-pass](https://github.com/eclipse-tractusx/digital-product-pass) repository
- Enabled branch and gh-pages relevant configurations 
- Guided information from EF and Otterdog Team https://github.com/eclipse-tractusx/.eclipsefdn/issues/28
FYI @stephanbcbauer 
> chore: enable branch protection rule and other configurations on digital-product-pass main branch

- otterdog/eclipse-tractusx.jsonnet
This PR renames an already existing (empty) repository. The new name fits to the already given `sldt-sematic-models`.
The repository configuration itself was not adapted.
> chore(repository): rename ontology repository

- otterdog/eclipse-tractusx.jsonnet
This PR will set [bpdm-upload-tool](https://github.com/eclipse-tractusx/bpdm-upload-tool) and [vas-country-risk-backend](https://github.com/eclipse-tractusx/vas-country-risk-backend) to public archive.
[bpdm-upload-tool](https://github.com/eclipse-tractusx/bpdm-upload-tool) is not maintained as of now and only contains the initial contribution.
[vas-country-risk-backend](https://github.com/eclipse-tractusx/vas-country-risk-backend) has been integrated in the monorepo [vas-country-risk](https://github.com/eclipse-tractusx/vas-country-risk)
> chore: archive BPDM upload tool and country risk backend

- otterdog/eclipse-tractusx.jsonnet
This PR deletes two unmaintained repositories. They are deleted instead of archived, because they are not even initialized.
Repos to delete: 
- [eclipse-tractusx/sig-testing](https://github.com/eclipse-tractusx/sig-testing)
- [eclipse-tractusx/quality-dashboard](https://github.com/eclipse-tractusx/quality-dashboard) -> Legal docs initialized 8 months ago. No activity since then
> chore: delete uninitialized repos

- otterdog/policies/macos_large_runners.yml
This PR allows the use of macos large runners in this organization as it has now been disabled by default for all orgs.
> Allow the use of macos large runners

- otterdog/eclipse-tractusx.jsonnet
We want to force the build for our main tractus-x webpage to be working and block the merge if not.
Workflow: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/main/.github/workflows/build-and-deploy-gh-pages.yaml#L30C11-L30C43
Closes eclipse-tractusx/eclipse-tractusx.github.io#1067
> feat(prs): block failing build for github pages

- otterdog/eclipse-tractusx.jsonnet
New repo for tractusx edc compatibility tests
Ref: https://github.com/eclipse-tractusx/sig-release/issues/908
> feat: new repo for tractus-x edc compatibility tests

- otterdog/eclipse-tractusx.jsonnet
This PR changes the action we are waiting for. 
- `Build static website`-> correct one -> checks if it is possible to build the page
- `Build and deploy to GitHub Pages`->  wrong one -> Builds and deploy to gh-pages after merge
> chore(branch protection): switch the action we are waiting for

- otterdog/eclipse-tractusx.jsonnet
This PR disables the branch protection (Waiting for a concrete action) because it didn't work probably.
> chore: revert changes

- otterdog/eclipse-tractusx.jsonnet
Since we are starting to scale the  Eclipse Tractus-X product to other dataspaces rather than just Catena-X, we need to start documenting the overall architecture and  here we can come together as multiple organizations to find a way forward in  fitting the general dataspace architecture of Tractus-X Manufacturing.
Closes #110 
- Added the sig-architecture repository, and basic description
- I enabled the github pages, so we can also add some static documentation.
- Added discussions so  we can  have threads to  discuss the architecture topics with the community
- Copied the configuration format from other "sig-*" repositories.
> feat(sig-architecture): created sig-architecture repository

- otterdog/eclipse-tractusx.jsonnet
In this repository will be hosted the new Industry Core Reference Implementation, called Industry Core Hub.
It will act as provider and consumer and provider a speed way for use cases that use it.
> feat: added the industry core hub repo

- otterdog/eclipse-tractusx.jsonnet
As aligned and refined in the sig-release feature: https://github.com/eclipse-tractusx/sig-release/issues/1161
And aligned with the community in the office hour and in the open meeting from the Industry Core Hub, there will be shifted the following folder: https://github.com/eclipse-tractusx/industry-core-hub/tree/main/tractusx_sdk
To a separated repository, following the pattern from the "Portal" which have multiple repositories for multiple components. In this case if you use the tractus-x sdk it will not be only restricted or attached to the Industry core hub repo.
It was proposed and included today during the Open Source Refinement for R25.06 our MVP target release.
The industry core hub will be the first "lighthouse" implementation of that tractus-x sdk. So it can be reused by other …
> feat: added tractus-x sdk repo for industry core hub

- otterdog/eclipse-tractusx.jsonnet
This PR should set main “read_only” for a small time period. Because we have a bigger maintenance phase and don't want to have other changes on main.
> chore(github.io): temporarily lock main branch on github.io

- otterdog/eclipse-tractusx.jsonnet
Since we are ready with our maintenance phase, we would like to remove the lock on the branches
> remove the protection on github.io

- otterdog/eclipse-tractusx.jsonnet
When applying KICS to markdown documents I've already received false positives. Now that I excluded it and only have a pr with documentation (see [here](https://github.com/eclipse-tractusx/puris/pull/884)), the kics run blocks the pr.
Thus I don't want it to be required.
> ci(puris): do not require kics

- otterdog/eclipse-tractusx.jsonnet
As described in this ticket: 
https://github.com/eclipse-tractusx/sig-release/issues/1467
Wind-X is willing to integrate the BaSyx Python SDK and the Tractus-X SDK in one runtime which is able to manage the Authorization and Usage Permissions in the EDC and provide Asset Administration Shells (AAS) as EDC Assets.
The idea is to create helm charts and host the images in docker hub, so therefore we need to create a repo to do the integration.
BaSyx Python SDK: https://github.com/eclipse-basyx/basyx-python-sdk
Tractus-X SDK: https://github.com/eclipse-tractusx/tractusx-sdk
> feat/aas-suite: Added new repository for integrating and generating a common runtime between BaSyx & Tractus-X SDK

- otterdog/eclipse-tractusx.jsonnet
As described in issues https://github.com/eclipse-tractusx/sig-release/issues/1496 and https://github.com/eclipse-tractusx/sig-release/issues/1528, this PR creates to new repositories.
The content for the repositories will be an outcome of CX-NEXT.
contactpersons:
- policy-builder -> @juliapampus
- engineering-use-case-demonstrator -> @bosserf, @FEILSTE
> add two new repositories

- otterdog/eclipse-tractusx.jsonnet
As described in this issue #135 and prepared at the digital-product-pass repository we shall deprecate the repository.
I am starting now the process described in the TRG: https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-09
In two weeks if there is no problem we can merge this PR
> feat: deprecate digital-product-pass repository
